### ISSUE TITLE
Secure assets above web root?

### ISSUE THREAD

**Issue by simonkuran** [masugadesign/link-vault-craft-cms#10]
Is it possible to secure assets by storing them above web root and have Link Vault serve them instead of linking to a public URL?

**Comment by ryanmasuga** [comment]
Sure. You can use an Asset element as the parameter, a system path to _anywhere_, or a URL. Check out Example 3 under the [downloadurl](https://github.com/masugadesign/link-vault-craft-cms#downloadurl) template variable.

**Comment by simonkuran** [comment]
Good to know, thanks.
