### ISSUE TITLE
Bucket/directory is not shown when using .env variable

### ISSUE THREAD

**Issue by lesaff** [masugadesign/link-vault-craft-cms#11]
- Plugin version: 3.1.4
- Craft version: Craft Pro 3.5.7
- PHP version: 7.4.9
- Database driver & version: MySQL 5.5.5

**Describe the bug**
Bucket/directory is not shown when using `env` variable.

**To Reproduce**
1. Use `env` variable to declare bucket name
2. View LinkVault page
3. See screenshot below

**Expected behavior**
Show the bucket or directory name

**Screenshots**
![Screen Shot 2020-08-27 at 3 27 16 PM](https://user-images.githubusercontent.com/1151181/91480913-0376e880-e87a-11ea-9e57-f8606ccb65e9.png)

**Additional context**

**Comment by benjaminkohl** [comment]
Environment variables should be evaluated before being used with Link Vault. Link Vault is just displaying the string value that is being passed to it.

**Comment by lesaff** [comment]
@benjaminkohl Are you implying that it's something to do with Craft not parsing the `env` var properly in this case?
