### ISSUE TITLE
Group count error

### ISSUE THREAD

**Issue by timprint** [masugadesign/link-vault-craft-cms#13]
I have copied the code from the groupCount example in the docs as a starting point.

```
{% set topDownloads = craft.linkvault.groupCount('fileName', {
    'userId' : currentUser.id,
    'order' : 'census desc'
}) %}
<ol>
{% for topDownload in topDownloads %}
    <li>{{ topDownload.fileName }} ({{ topDownload.census|number_format(0) }} downloads)</li>
{% endfor %}
</ol>
```

I have done some test downloads and craft.linkvault.downloads and craft.linkvault.records are both working as expected but the groupCount example code above produces the following error.

```
Database Exception – yii\db\Exception
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'order' in 'where clause'
The SQL being executed was: SELECT `fileName`, COUNT(*) AS `census`
FROM `linkvault_downloads`
WHERE (`userId`=1) AND (`order`='census desc')
GROUP BY `fileName`
ORDER BY COUNT(*) DESC
LIMIT 100

Error Info: Array
(
    [0] => 42S22
    [1] => 1054
    [2] => Unknown column 'order' in 'where clause'
)
```

Any idea what could be wrong?

**Comment by ryanmasuga** [comment]
What version of Craft and Link Vault?

**Comment by benjaminkohl** [comment]
There will be a fix for this in the next release. Until then, removing that "order" parameter should prevent the error and the results will be sorted by highest count, descending by default.

**Comment by timprint** [comment]
Thank you. That's working. I have another question but will open a separate issue.
