### ISSUE TITLE
403 Error When Using Plugin

### ISSUE THREAD

**Issue by AbbeyDesign** [masugadesign/link-vault-craft-cms#17]
**Describe the bug**  
Not sure this is a bug(probably not a bug), or I just installed it wrong, or if I have to do an extra step that I could not find in the docs.

I added this code: 

`{% for file in assets %}
     {{ craft.linkvault.downloadUrl(file) }}
{% endfor %}`

to an asset loop but I get an error:

HTTP 403 – Forbidden – yii\web\ForbiddenHttpException
You are not authorized to access this resource.
and down the page a little, I get this:

// blockLeechAttempts is enabled AND a leech attempt was detected.

So my guess is I have to set up the siteUrl somehow? The asset is in an S3 bucket.

**Comment by AbbeyDesign** [comment]
Can I get a response? Do you need more info from my end?

**Comment by benjaminkohl** [comment]
Are the generated links displayed in an email or on a page that has a different base URL than your site? That would trigger a leech attempt. You could disable leech blocking in the Link Vault config if there are situations where the base site URL changes on your site for some reason.

```
'blockLeechAttempts' => false,
```

Also, are you saying that "// blockLeechAttempts is enabled AND a leech attempt was detected." is being displayed on the page? That is a PHP code comment in the Link Vault plugin. That should never appear on a rendered page. If you are seeing that on the page, I can't think of any reason that would be happening.

**Comment by AbbeyDesign** [comment]
No. That code is on a page within the site. The error I am seeing is just the yii error page because I have devmode on. It actually crashes my server when I click on the link. I just turned set "block leech attempts" to false and it works as expected, but, that defeats the purpose? 

A small detail that I failed to include that may be the cause? I just thought about it now. I am using mamp locally and maybe Mamp does something behind the scenes with the url. I will try on production with blockLeechAttempts to true.

**Comment by AbbeyDesign** [comment]
It's not Mamp. Production server with  blockLeechAttempts set to true clicking the link gives me this error(and crashes the server.

Unauthorized
You are not authorized to access this resource.

**Comment by benjaminkohl** [comment]
Very peculiar. Can you place the following line of code in `vendor/masugadesign/linkvault/src/controllers/LinkVaultController.php` on line 88, immediately before the "return" statement in the method called `isLeechAttempt()`

```
exit("{$referringDomain} - {$siteDomain}");
```

Once that is in place, try clicking one of your links. It should dump these strings to your browser window. In theory, both strings should be the same but they clearly aren't if each download attempt is being treated as a leech attempt. That's what makes me think the base URL for your site is somehow different than the generated download link URLs but Link Vault uses the Craft `UrlHelper` class to generate URLs so they really should be consistent except in unusual scenarios.

**Comment by benjaminkohl** [comment]
@AbbeyDesign Were you able to resolve this issue on your end or is there a fix we need to make?

**Comment by benjaminkohl** [comment]
Closing this one due to inactivity.
