### ISSUE TITLE
Masuga\LinkVault\services\FilesService\parseEnvironmentString method doesn't exist

### ISSUE THREAD

**Issue by i-just** [masugadesign/link-vault-craft-cms#20]
Hi,

It looks like `Masuga\LinkVault\services\FilesService\parseEnvironmentString` method doesn't exist. 
I can see there's a variable called `parseEnvironmentString` (line 165 of `src/variables/LinkVaultVariable.php`) which references `$this->plugin->files->parseEnvironmentString($string)`. However in `src/services/FilesService.php` there's no method called `parseEnvironmentString`.

You do reference using that variable in Example 2 in instructions on how to use your plugin: https://github.com/masugadesign/link-vault-craft-cms#template-variables. 

Not sure what this method used to do, but you might want to either add it back in or amend the instructions.

Craft CMS version: 4.0.4
LinkVault version: 4.0.1

**Comment by benjaminkohl** [comment]
Thanks for bring that to my attention. I'll remove all references to that in the next release. I believe it is left over from the old Craft 2 version of the plugin.

**Comment by benjaminkohl** [comment]
This issue was resolved in [v4.0.2](https://github.com/masugadesign/link-vault-craft-cms/blob/master/CHANGELOG.md#402---2022-06-10).
