### ISSUE TITLE
Remove past leech attempts

### ISSUE THREAD

**Issue by bartrylant** [masugadesign/link-vault-craft-cms#22]
I have one user (not logged in) who is accidentally marked as leecher. How can I remove the block so he can download files again?

**Comment by benjaminkohl** [comment]
A download attempt is flagged as a leech attempt any time any user tries to access a download URL from somewhere other than the site. You can disable leech blocking by setting "blockLeechAttempts" to _false_ in the [Link Vault config](https://github.com/masugadesign/link-vault-craft-cms#config-variables).
