### ISSUE TITLE
remote URLs with no file extension fail

### ISSUE THREAD

**Issue by booyaamps** [masugadesign/link-vault-craft-cms#23]
We are storing remote FetchApp URLs for ebooks and are trying to use Link Vault to generate/control the random URLs for download so we can prevent leaching.
When trying to generate a downloadUrl with a remote URL that has no file extension (i.e. https://our.fetchapp.url/permalink/8de825 ) we get the following twig error:

Undefined array key "extension"

$element->downloadAs = isset($recordData['downloadAs']) ? $recordData['downloadAs'] : $fileParts['filename'].'.'.$fileParts['extension'];

**Craft Version & Installed Plugin Version**  
Craft:   3.8.7
Plugin: 3.2.0

**Comment by benjaminkohl** [comment]
Hi, @booyaamps. I just released Link Vault v3.2.1 which addresses this error that occurs during the logging of downloads from remote URLs that do not contain filenames in the URI.

**Comment by booyaamps** [comment]
Hi, thank you for the speedy fix! However i'm also getting this same error when calling the totalDownloads template variable:

Undefined array key "extension"
 in /var/www/html/vendor/masugadesign/linkvault/src/services/GeneralService.php at line 151

**Comment by benjaminkohl** [comment]
What type of parameter value are you supplying to the `totalDownloads(param)` template variable?

**Comment by booyaamps** [comment]
craft.linkvault.totalDownloads(item.purchasable.ebook,{userEmail : craft.session.getUser().email, elementId : item.purchasable.id}) 

item.purchasable.ebook is the URL from our filesystem provider.

**Comment by booyaamps** [comment]
i'm using the same array of params for the downloadUrl function. Basically im trying to see how many times a certain email address has used that download link, and if its 3 times, restricting access to prevent unlimited downloads.

**Comment by benjaminkohl** [comment]
Ah, with the [totalDownloads variable](https://github.com/masugadesign/link-vault-craft-cms#totaldownloads), it only accepts a single parameter. If you'd like to use an array for that parameter, it could look like this (assuming `userEmail` is a custom Link Vault field you created, otherwise use `userId`):

```
craft.linkvault.totalDownloads({
    userEmail: currentUser.email,
    elementId: item.purchasable.id
})
```

If each purchasable may have more than one downloadable file associated with it and you need to query for a specific one, you can do this:

```
craft.linkvault.totalDownloads({
    fileName: theEbookUrl,
    userEmail: currentUser.email,
    elementId: item.purchasable.id
})
```

Link Vault stores the full URL as the fileName for remote URLs since some URLs don't have actual fileNames in them.

**Comment by booyaamps** [comment]
ahhh you rock! that did it! thank you!!

**Comment by benjaminkohl** [comment]
I'm glad to hear it is working for you!
