### ISSUE TITLE
Download links not working in multi-site setup

### ISSUE THREAD

**Issue by thisisjamessmith** [masugadesign/link-vault-craft-cms#3]
- Plugin version: 3.0.5.1
- Craft version: 3.0.29
- PHP version: 7.1.12

**Describe the bug**

I'm testing this plugin in a multi-site setup, where the protected links are on site-2. Clicking a link-vault download link results in an error in Craft's log (storage/logs/web.log) stating `Attempting to save an element in an unsupported site`, generated by line 264 of GeneralService.php (`$saveStatus = Craft::$app->elements->saveElement($element);`)

**To Reproduce**

1. Setup two sites in Craft
2. Create Link-Vault protected links on the site that's not the primary site
3. Click that link

**Potential fix**

Adding the following code at the end of the `elements/LinkVaultDownload.php` class appears to fix the problem, but I'm not 100% sure what the knock-on effects of this might be:

```
public static function isLocalized(): bool
{
	return true;
}
```

**Comment by benjaminkohl** [comment]
I just released Link Vault 3.0.5.2 which contains this fix.
