### ISSUE TITLE
"Couldn't install plugin" after updating from Craft 2

### ISSUE THREAD

**Issue by JayBox325** [masugadesign/link-vault-craft-cms#4]
- Plugin version: 3.0.5.2
- Craft version: 3.1.12
- PHP version: 7.1.12
- Database driver & version: 

**Describe the bug**
After updating from Craft 2 site that used LinkVault to Craft 3, I have re-installed the Craft 3 version of LinkVault. The plugin installs perfectly via composer, however, when I click 'install' in the CMS I get "Plugin couldn't be installed".

**Comment by benjaminkohl** [comment]
Do you see any errors in your error log pertaining to the failed installation?

**Comment by JayBox325** [comment]
```
Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column ‘settings’ in ‘field list’
The SQL being executed was: SELECT `id`, `settings`, `handle`
FROM `craft_plugins`
WHERE (`handle`=‘linkVault’) AND (`version` < ‘3.0.0’)
```

**Comment by benjaminkohl** [comment]
Thanks. May I have the stack trace that accompanied that error so I can figure out where it is taking place in the code?

**Comment by JayBox325** [comment]
It appears that Craft 3 deletes the settings line in the SQL tables when it upgrades from Craft 2. So LinkVault looks for a line in the database that no longer exists.

**Comment by benjaminkohl** [comment]
The settings column existed in Craft 3 but has apparently been removed in Craft 3.1 but I am having trouble tracking down a proper upgrade guide on how this should be handled if the plugin needs to make the jump from Craft 2 straight to Craft 3.1. I'm looking into it.

**Comment by JayBox325** [comment]
No worries, we resolved it by adding the settings line back into the database while we installed LinkVault and just dropped it afterwards. At least we got to the bottom of it. Good luck!

**Comment by benjaminkohl** [comment]
Ok, that is what I was just about to recommend, actually. I'm glad that worked! I'll add some additional checks to the upgrade process for Link Vault so others don't run into the same issue.
