### ISSUE TITLE
Couldn’t install plugin.

### ISSUE THREAD

**Issue by kevincarpdev** [masugadesign/link-vault-craft-cms#5]
- Plugin version: 3.0.5.2
- Craft version: 3.1.15
- PHP version: 7.1

Purchased the plugin, and when i go to install it, I just get the basic craft error alert "Couldn’t install plugin."

Any advice?

**Comment by benjaminkohl** [comment]
This is most likely due to Craft 3.1 dropping the "settings" column from the plugins table. If you just add that column back to the table, it should work. Someone else had this same problem recently: [Couldn't Install Plugin](https://github.com/masugadesign/link-vault-craft-cms/issues/4)

**Comment by kevincarpdev** [comment]
That worked! Thanks for the timely reply!
