### ISSUE TITLE
Limit the number of downloads for a file

### ISSUE THREAD

**Issue by rob-c-baker** [masugadesign/link-vault-craft-cms#8]
- Plugin version: 3.0.5.3
- Craft version: 3.1.24
- PHP version: 7.2.17
- Database driver & version: MySQL 5.7.26

I can see it's possible to get the number of times a file has been downloaded but how do I ensure a file can only be downloaded a certain number of times?

I am setting up a Craft Commerce store to deliver PDFs once purchased, I have got to the point where the items can be purchased using Pixel & Tonic's "Digital Products" plugin for Commerce 2. I then generate a link with your plugin which limits the download to the logged in user but it seems they can use that link as many times as they want.

I am using a Craft 3 volume attached to an Amazon S3 bucket to store the files.

**To Reproduce**
Generate a link from a Asset field attached to a Craft 3 volume using Amazon S3 with Pixel & tonic's Amazon S3 integration.

**Expected behavior**
Have a way to ensure the link can be used a set number of times.

**Comment by benjaminkohl** [comment]
Once you fetch the download count, you can just wrap the download link in a conditional that compares the number of downloads to whatever limit you want to set.

```
{% if totalDownloads < downloadLimit %}
   ...show the link...
{% else %}
   Download limit has been reached.
{% endif %}
```

**Comment by benjaminkohl** [comment]
The second part of this would be to block leech attempts in the [Link Vault config](https://gomasuga.com/software/link-vault-for-craft-cms/installation-setup#configuration%20variables-doc) so a link can't be saved by the user or passed around to other people.

**Comment by rob-c-baker** [comment]
Hi @benjaminkohl thanks for this. 

I have something along these lines in place now. in your example above though, `totalDownloads` - as supplied by the link vault plugin - ends up being the total number of times a file has been downloaded for any user / order. I really need that to become "per order placed".

Do you know of a way to make that happen?

**Comment by ryanmasuga** [comment]
Are those downloads taking place on an order page, or somewhere where you can get the order number? If so, you might be able to store the order number in a Link Vault custom field on the downloads, then adjust the total downloads query to account for matching the value in that custom field.

**Comment by rob-c-baker** [comment]
That's a good idea. I'll have a go at that. Thanks.
